/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'sci.peer.article'

export { $nsid }

type Block = {
  $type?: 'sci.peer.article#block'

  /**
   * 階層の深さ。1:section, 2:subsection, 3:subsubsection...
   */
  level: number

  /**
   * セクションの見出し
   */
  heading: string

  /**
   * TeXまたはMarkdown形式の本文
   */
  content: string
}

export type { Block }

type Citation = {
  $type?: 'sci.peer.article#citation'

  /**
   * BibTeX citation key
   */
  key: string

  /**
   * Raw BibTeX entry
   */
  rawBibtex: string
}

export type { Citation }

const citation = l.typedObject<Citation>(
  $nsid,
  'citation',
  l.object({
    key: l.string(),
    rawBibtex: l.string(),
  }),
)

export { citation }

const block = l.typedObject<Block>(
  $nsid,
  'block',
  l.object({
    level: l.integer({ minimum: 1, maximum: 6 }),
    heading: l.string(),
    content: l.string(),
  }),
)

export { block }

type Main = {
  $type: 'sci.peer.article'

  /**
   * 論文または実験計画のタイトル
   */
  title: string

  /**
   * 論文を構成する任意のセクション配列（フラット構造）
   */
  blocks: Block[]
  bibliography?: Citation[]
  createdAt: l.DatetimeString
}

export type { Main }

const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    title: l.string({ maxLength: 300 }),
    blocks: l.array(l.ref<Block>((() => block) as any)),
    bibliography: l.optional(l.array(l.ref<Citation>((() => citation) as any))),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
